In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np

In [33]:
#sentences = data["description"]
df = pd.read_csv("D:/assignment/7102/program data_pre(ver2)(1).csv")
df


Schoole                                            program  \
0         SAIC      Architecture, Interior Arch, Designed Objects   
1         SAIC                                 Art and Technology   
2         SAIC                                      Art Education   
3         SAIC                                        Art History   
4         SAIC                                        Art Therapy   
..         ...                                                ...   
149  Edinburgh  Professional Experience Support: UK Part 3 (AR...   
150  Edinburgh                                 Sound Design - MSc   
151  Edinburgh                               Textiles - BA (Hons)   
152  Edinburgh         Updates in Architectural Management course   
153  Edinburgh                  Urban Strategies and Design - MSc   

                                           description  
0    ['relate', 'artmaking', 'approach', 'pedagogy'...  
1    ['medium', 'introduces', 'graduate', 'student'...  
2    ['student', 'deepen', 'approach', 'fashion', '...  
3    ['discussion', 'examine', 'documentation', 'an...  
4    ['consultation', 'study', 'student', 'spend', ...  
..                                                 ...  
149  ['arb', 'riba', 'title', 'examination', 'pract...  
150  ['study', 'msc', 'design', 'expand', 'apprecia...  
151  ['texture', 'form', 'department', 'continue', ...  
152  ['aim', 'candidate', 'arb', 'riba', 'examinati...  
153  ['study', 'msc', 'strategy', 'design', 'eca', ...  

[154 rows x 3 columns]

In [34]:
content = df['description']
sentences = []
for i in range(len(content)):
    a = content[i]
    a = a.replace(","," ")
    a = a.replace("'","")
    a = a.replace("[","")
    a = a.replace("]","")
    sentences.append(a)
#sentences

In [35]:
vectorizer = TfidfVectorizer(norm = None)
X = vectorizer.fit_transform(sentences)
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# Ordering all words by tfidf

In [37]:
#print(vectorizer.vocabulary_)
#print(vectorizer.get_feature_names())
#print(X)
print(X.shape)
word = {"word":vectorizer.get_feature_names(), 'tfidf':X.toarray().sum(axis=0).tolist()}
word = pd.DataFrame(word)
word.sort_values(by='tfidf',ascending = False)

(154, 4882)


e:\anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


word        tfidf
4306     student  3698.903098
782        class  1775.577038
3517     project  1588.427204
1189      design  1232.611571
4309      studio  1046.531154
...          ...          ...
2331      invest     5.350278
2334  invitation     5.350278
2338          ip     5.350278
2339    iplayers     5.350278
4881        zora     5.350278

[4882 rows x 2 columns]

# words and tfidf for each document

In [38]:
# create a dictionary to store the word/key and tfidf/value
dict_of_tokens = {i[1]:i[0] for i in vectorizer.vocabulary_.items()}
tfidf_vectors = []
for row in X:
    tfidf_vectors.append({dict_of_tokens[column]:value for (column,value) in zip(row.indices,row.data)})


#words for document 0
print(tfidf_vectors[0])
#words for document 1
print(tfidf_vectors[1])

{'con': 4.944812828251137, 'aesthetic': 3.47847575945771, 'ethic': 3.846200539583027, 'discus': 4.433987204485146, 'session': 3.740840023925201, 'performance': 2.8245492920510458, 'endeavor': 4.657130755799356, 'collaborate': 4.433987204485146, 'methodology': 3.0476928433652555, 'transformation': 4.433987204485146, 'force': 3.846200539583027, 'identity': 3.2102117728630306, 'reimaging': 5.350277936359301, 'recombine': 5.350277936359301, 'hartman': 4.944812828251137, 'appadurai': 4.944812828251137, 'arjun': 4.944812828251137, 'oz': 4.944812828251137, 'mu': 4.944812828251137, 'vizenor': 4.944812828251137, 'gerald': 4.944812828251137, 'campt': 4.944812828251137, 'tina': 4.944812828251137, 'russell': 4.944812828251137, 'hall': 4.944812828251137, 'stuart': 4.433987204485146, 'audra': 4.944812828251137, 'tuck': 4.657130755799356, 'market': 3.645529844120876, 'flea': 4.944812828251137, 'informal': 4.657130755799356, 'harold': 4.944812828251137, 'harsch': 4.944812828251137, 'ayers': 4.94481282

# Select the first 10 words as keywords

In [39]:
keyword_vectors = []
for i in range(len(tfidf_vectors)):
    document_i = tfidf_vectors[i]
    if len(document_i) <= 10:    #保留整个document的words
        keyword_vectors.append(document_i) 
    else:
        a = sorted(document_i.items(), key=lambda document_i: document_i[1], reverse=True)
        for j in range(len(a)-1,9,-1):  #从后往前删除
            #if a[j][1] != a[9][1]:
                a.pop(j)
        keyword_vectors.append(dict(a)) 
        

In [40]:
#key words for document 0
print(keyword_vectors[0])


#key words for document 1
print(keyword_vectors[1])

{'student': 162.33430523065857, 'teach': 113.87126548324979, 'school': 112.98197168204183, 'community': 85.96113859713903, 'standard': 85.40444321114991, 'placement': 83.82835360438841, 'learn': 76.407526663583, 'teacher': 75.3156879295488, 'artmaking': 74.5140920927897, 'project': 72.97521612825066}
{'student': 168.13195898889637, 'medium': 73.03120003922189, 'game': 69.65775445368686, 'art': 68.74164652550972, 'experience': 54.79819616111611, 'skill': 53.586620154943596, 'technique': 51.80000458171682, 'sound': 51.36338836580849, 'light': 50.00060701457935, 'therapy': 48.77385924933661}


In [30]:
D = pd.DataFrame(keyword_vectors[0].keys())


for i in range(1,len(keyword_vectors)):
    df_b = pd.DataFrame(keyword_vectors[i].keys())
    D = pd.concat([D.reset_index(drop=True), df_b], axis=1)


In [31]:
D = D.T
D.to_excel("keywords_program(2).xlsx", header=True, index=True, engine='openpyxl')

# Topic finding using LDA

In [44]:
from gensim import corpora, models

In [45]:
# list_of_list_of_tokens = [["a","b","c"], ["d","e","f"]]
# ["a","b","c"] are the tokens of document 1, ["d","e","f"] are the tokens of document 2...
content = df['program']
list_of_list_of_tokens = []
for i in range(len(content)):
    a = content[i]
    a = a.replace(","," ")
    a = a.replace("'","")
    a = a.replace("[","")
    a = a.replace("]","")
    list_of_list_of_tokens.append(a.split(" "))

In [46]:
dictionary_LDA = corpora.Dictionary(list_of_list_of_tokens)
dictionary_LDA.filter_extremes(no_below=3)
corpus = [dictionary_LDA.doc2bow(list_of_tokens) for list_of_tokens in list_of_list_of_tokens]

num_topics = 2 #can change this number of topic
lda_model = models.LdaModel(corpus, num_topics=num_topics, 
                            id2word=dictionary_LDA,                                   
                            passes=4, alpha=[0.01]*num_topics,
                            eta=[0.01]*len(dictionary_LDA.keys()))

In [47]:
#print topic found:
for i,topic in lda_model.show_topics(formatted=True, num_topics=num_topics, num_words=30):
    print(str(i)+": "+ topic)
    print()

0: 0.232*"Art" + 0.184*"and" + 0.090*"-" + 0.038*"(Hons)" + 0.032*"History" + 0.025*"the" + 0.023*"MSc" + 0.022*"MA" + 0.021*"Technology" + 0.021*"Architecture" + 0.020*"BA" + 0.019*"Contemporary" + 0.018*"Studies" + 0.016*"Photography" + 0.016*"Culture" + 0.016*"Practice" + 0.016*"Landscape" + 0.016*"PhD" + 0.016*"Fashion" + 0.016*"Education" + 0.016*"Cultural" + 0.015*"by" + 0.015*"Visual" + 0.014*"in" + 0.014*"Music" + 0.011*"of" + 0.011*"Fine" + 0.006*"Masters" + 0.006*"Film" + 0.006*"Media"

1: 0.129*"-" + 0.086*"Design" + 0.081*"in" + 0.059*"Arts" + 0.049*"(Hons)" + 0.047*"and" + 0.046*"BA" + 0.045*"of" + 0.038*"MSc" + 0.038*"MPhil" + 0.030*"Digital" + 0.030*"Bachelor" + 0.029*"Media" + 0.029*"Film" + 0.025*"Architectural" + 0.024*"MA" + 0.024*"&" + 0.023*"Studies" + 0.020*"" + 0.019*"MPhil-PhD" + 0.015*"History" + 0.015*"Interior" + 0.015*"Fine" + 0.015*"Sound" + 0.012*"Music" + 0.010*"Distance" + 0.010*"Education" + 0.010*"Performance" + 0.009*"Masters" + 0.006*"Architecture"



In [48]:
#To print the % of topics a document is about, do the following:
#(14, 0.9983065953654187)means the first document is 99.8% about topic 14.

lda_model[corpus[0]] # corpus[0] means the first document.

[(1, 0.99751234)]

# Repeat the process for job dataset version 2

In [3]:
#sentences = data["description"]
df2 = pd.read_csv("D:/assignment/7102/program data_pre(ver2).csv")
df2

Schoole                                            program  \
0         SAIC      Architecture, Interior Arch, Designed Objects   
1         SAIC                                 Art and Technology   
2         SAIC                                      Art Education   
3         SAIC                                        Art History   
4         SAIC                                        Art Therapy   
..         ...                                                ...   
149  Edinburgh  Professional Experience Support: UK Part 3 (AR...   
150  Edinburgh                                 Sound Design - MSc   
151  Edinburgh                               Textiles - BA (Hons)   
152  Edinburgh         Updates in Architectural Management course   
153  Edinburgh                  Urban Strategies and Design - MSc   

                                           description  
0    ['relate', 'artmaking', 'approach', 'pedagogy'...  
1    ['medium', 'introduces', 'graduate', 'student'...  
2    ['student', 'deepen', 'approach', 'fashion', '...  
3    ['discussion', 'examine', 'documentation', 'an...  
4    ['consultation', 'study', 'student', 'spend', ...  
..                                                 ...  
149  ['arb', 'riba', 'title', 'examination', 'pract...  
150  ['study', 'msc', 'design', 'expand', 'apprecia...  
151  ['texture', 'form', 'department', 'continue', ...  
152  ['aim', 'candidate', 'arb', 'riba', 'examinati...  
153  ['study', 'msc', 'strategy', 'design', 'eca', ...  

[154 rows x 3 columns]

In [4]:
content2 = df2['description']
sentences2 = []
for i in range(len(content2)):
    a = content2[i]
    a = a.replace(","," ")
    a = a.replace("'","")
    a = a.replace("[","")
    a = a.replace("]","")
    sentences2.append(a)
#sentences

In [5]:
vectorizer2 = TfidfVectorizer(norm = None)
X2 = vectorizer2.fit_transform(sentences2)

In [6]:
print(X2.shape)
word2 = {"word":vectorizer2.get_feature_names(), 'tfidf':X2.toarray().sum(axis=0).tolist()}
word2 = pd.DataFrame(word2)
word2.sort_values(by='tfidf',ascending = False)

(154, 4882)


e:\anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


word        tfidf
4306     student  3698.903098
782        class  1775.577038
3517     project  1588.427204
1189      design  1232.611571
4309      studio  1046.531154
...          ...          ...
2331      invest     5.350278
2334  invitation     5.350278
2338          ip     5.350278
2339    iplayers     5.350278
4881        zora     5.350278

[4882 rows x 2 columns]

In [7]:
# create a dictionary to store the word/key and tfidf/value
dict_of_tokens2 = {i[1]:i[0] for i in vectorizer2.vocabulary_.items()}
tfidf_vectors2 = []
for row in X2:
    tfidf_vectors2.append({dict_of_tokens2[column]:value for (column,value) in zip(row.indices,row.data)})


#words for document 0
print(tfidf_vectors2[0])
#words for document 1
print(tfidf_vectors2[1])

{'con': 4.944812828251137, 'aesthetic': 3.47847575945771, 'ethic': 3.846200539583027, 'discus': 4.433987204485146, 'session': 3.740840023925201, 'performance': 2.8245492920510458, 'endeavor': 4.657130755799356, 'collaborate': 4.433987204485146, 'methodology': 3.0476928433652555, 'transformation': 4.433987204485146, 'force': 3.846200539583027, 'identity': 3.2102117728630306, 'reimaging': 5.350277936359301, 'recombine': 5.350277936359301, 'hartman': 4.944812828251137, 'appadurai': 4.944812828251137, 'arjun': 4.944812828251137, 'oz': 4.944812828251137, 'mu': 4.944812828251137, 'vizenor': 4.944812828251137, 'gerald': 4.944812828251137, 'campt': 4.944812828251137, 'tina': 4.944812828251137, 'russell': 4.944812828251137, 'hall': 4.944812828251137, 'stuart': 4.433987204485146, 'audra': 4.944812828251137, 'tuck': 4.657130755799356, 'market': 3.645529844120876, 'flea': 4.944812828251137, 'informal': 4.657130755799356, 'harold': 4.944812828251137, 'harsch': 4.944812828251137, 'ayers': 4.94481282

# Select the first 10 words as keywords

In [8]:
keyword_vectors2 = []
for i in range(len(tfidf_vectors2)):
    document_i = tfidf_vectors2[i]
    if len(document_i.keys()) <= 10:    #保留整个document的words
        keyword_vectors2.append(document_i) 
    else:
        a = sorted(document_i.items(), key=lambda document_i: document_i[1], reverse=True)
        for j in range(len(a)-1,9,-1):  #从后往前删除
            #if a[j][1] != a[9][1]:
                a.pop(j)
        keyword_vectors2.append(dict(a)) 
        

In [9]:
#key words for document 0
print(keyword_vectors2[0])


#key words for document 1
print(keyword_vectors2[1])

{'student': 162.33430523065857, 'teach': 113.87126548324979, 'school': 112.98197168204183, 'community': 85.96113859713903, 'standard': 85.40444321114991, 'placement': 83.82835360438841, 'learn': 76.407526663583, 'teacher': 75.3156879295488, 'artmaking': 74.5140920927897, 'project': 72.97521612825066}
{'student': 168.13195898889637, 'medium': 73.03120003922189, 'game': 69.65775445368686, 'art': 68.74164652550972, 'experience': 54.79819616111611, 'skill': 53.586620154943596, 'technique': 51.80000458171682, 'sound': 51.36338836580849, 'light': 50.00060701457935, 'therapy': 48.77385924933661}


In [10]:
D2 = pd.DataFrame(keyword_vectors2[0].keys())


for i in range(1,len(keyword_vectors2)):
    df_b = pd.DataFrame(keyword_vectors2[i].keys())
    D2 = pd.concat([D2.reset_index(drop=True), df_b], axis=1)

    
D = D.T
D.to_excel("keywords_program(2).xlsx", header=True, index=True, engine='openpyxl')

NameError: name 'D' is not defined

# Topic finding

In [58]:
# list_of_list_of_tokens = [["a","b","c"], ["d","e","f"]]
# ["a","b","c"] are the tokens of document 1, ["d","e","f"] are the tokens of document 2...
content2 = df2['description']
list_of_list_of_tokens2 = []
for i in range(len(content2)):
    a = content2[i]
    a = a.replace(","," ")
    a = a.replace("'","")
    a = a.replace("[","")
    a = a.replace("]","")
    list_of_list_of_tokens2.append(a.split(" "))

In [59]:
dictionary_LDA2 = corpora.Dictionary(list_of_list_of_tokens2)
dictionary_LDA2.filter_extremes(no_below=3)
corpus2 = [dictionary_LDA2.doc2bow(list_of_tokens) for list_of_tokens in list_of_list_of_tokens2]

num_topics = 2 #can change this number of topic
lda_model2 = models.LdaModel(corpus2, num_topics=num_topics, 
                            id2word=dictionary_LDA2,                                   
                            passes=4, alpha=[0.01]*num_topics,
                            eta=[0.01]*len(dictionary_LDA2.keys()))

In [60]:
#print topic found:
for i,topic in lda_model2.show_topics(formatted=True, num_topics=num_topics, num_words=10):
    print(str(i)+": "+ topic)
    print()

0: 0.048*"student" + 0.024*"project" + 0.017*"semester" + 0.017*"practice" + 0.016*"graduate" + 0.015*"study" + 0.013*"focus" + 0.013*"class" + 0.013*"studio" + 0.013*"painting"

1: 0.048*"student" + 0.019*"design" + 0.018*"class" + 0.013*"project" + 0.012*"explore" + 0.009*"practice" + 0.008*"artist" + 0.008*"reading" + 0.008*"studio" + 0.007*"develop"



In [61]:
#To print the % of topics a document is about, do the following:
#(14, 0.9983065953654187)means the first document is 99.8% about topic 14.

lda_model2[corpus2[0]] # corpus[0] means the first document.

[(0, 0.9999944)]